"""No Pydantic response_model here on purpose: this endpoint passes through
a static, already-validated JSON artifact (generated by
analysis/src/export_metrics.py) rather than data computed fresh per
request -- a full nested schema would just re-describe a structure that's
already fixed at generation time.
"""

from fastapi import APIRouter, HTTPException

from app.services import performance

router = APIRouter()


@router.get("/model/performance")
def get_model_performance() -> dict:
    try:
        return performance.get_performance()
    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=503,
            detail="Model evaluation metrics not available — run analysis/src/export_metrics.py",
        ) from exc
